import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#1d2a27',
  muted: '#66736f',
  paper: '#f6f1e8',
  panel: '#fffdf8',
  line: '#e4ddd0',
  rust: '#c65d3a',
  amber: '#e3a43a',
  moss: '#4f7b63',
  mint: '#dceee2',
  sky: '#d8eaf0',
};

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper },
  content: { paddingHorizontal: 18, paddingBottom: 36 },
  header: { paddingTop: 18, paddingBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  eyebrow: { color: colors.rust, fontSize: 12, fontWeight: '800', letterSpacing: 1.4, textTransform: 'uppercase' },
  title: { color: colors.ink, fontSize: 34, lineHeight: 38, fontWeight: '800', marginTop: 5 },
  caption: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  locationDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.rust, marginTop: 8 },
  card: { backgroundColor: colors.panel, borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 17, marginTop: 14 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 },
  cardTitle: { color: colors.ink, fontWeight: '800', fontSize: 18 },
  sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  weatherCard: { backgroundColor: colors.ink, borderRadius: 22, padding: 18, marginTop: 14 },
  weatherTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  weatherTitle: { color: '#d9e8de', fontSize: 13, fontWeight: '700' },
  temperature: { color: '#fffdf8', fontSize: 50, lineHeight: 56, fontWeight: '800', marginTop: 5 },
  degree: { fontSize: 24, fontWeight: '500' },
  risk: { color: '#f4c77c', fontSize: 13, fontWeight: '800', marginTop: 7 },
  weatherAdvisory: { color: '#c4d3cc', fontSize: 14, lineHeight: 20, marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#40514a' },
  refugeName: { color: colors.ink, fontSize: 22, fontWeight: '800', lineHeight: 26, marginBottom: 5 },
  refugeMeta: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  badge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 99, backgroundColor: colors.mint },
  badgeText: { color: colors.moss, fontSize: 12, fontWeight: '800' },
  badgeUnknown: { backgroundColor: '#eee9df' },
  badgeUnknownText: { color: colors.muted },
  action: { backgroundColor: colors.rust, borderRadius: 12, minHeight: 48, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', marginTop: 15 },
  actionText: { color: '#fffdf8', fontSize: 15, fontWeight: '800' },
  secondaryAction: { backgroundColor: colors.sky },
  secondaryActionText: { color: colors.ink },
  option: { borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 12 },
  optionName: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  optionMeta: { color: colors.muted, fontSize: 13, marginTop: 4 },
  summary: { color: colors.ink, fontSize: 19, lineHeight: 27, fontWeight: '700' },
  detailToggle: { color: colors.rust, fontWeight: '800', fontSize: 14, marginTop: 14 },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 13 },
  detailItem: { width: '47%', backgroundColor: colors.paper, borderRadius: 10, padding: 10 },
  detailLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  detailValue: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 3 },
  map: { height: 250, borderRadius: 16, overflow: 'hidden', marginTop: 12 },
  routeTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginTop: 8 },
  routeMeta: { color: colors.muted, fontSize: 14, marginTop: 3 },
  step: { flexDirection: 'row', paddingVertical: 11, borderTopWidth: 1, borderTopColor: colors.line },
  stepNumber: { color: colors.rust, fontWeight: '800', width: 28 },
  stepInstruction: { color: colors.ink, fontSize: 14, flex: 1, lineHeight: 19 },
  stepDistance: { color: colors.muted, fontSize: 12, marginLeft: 8 },
  error: { color: colors.rust, fontSize: 14, lineHeight: 20, marginTop: 12 },
  loading: { color: colors.muted, fontSize: 14, marginTop: 8 },
  footer: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 18, textAlign: 'center' },
});
